<header id="alert">
           
<div id="content" class="alert-banner-levelone"style="margin-bottom:8px;" >

<div id="left" class="alert-banner-leveltwo">&nbsp;<a href="#" style="color: #fff; background-color:#c0143c;padding:4px;float:left;"><i class="fa fa-warning"></i>&nbsp;ALERT&nbsp;</a>

<div id="right" class="alert-banner-levelthree" style="border:3px solid #c0143c;padding:1px;float:left;">&nbsp;&nbsp;NHLBI TPS Report System Offline for Scheduled Maintenance: Friday, 7/22, 12:00 AM to 5:00 AM.&nbsp;<a href="" style="color:#c0143c;"><i class="fa fa-info-circle alert-banner-color"></i></a>&nbsp;</div>

</div>

</div> 

</header>