<!-- Modal - About   -->
  <div class="modal fade" id="appAction" role="dialog" aria-labelledby="Description for About " tabindex="-1" style="background-color:#EBEBEB;" >
    <div class="modal-dialog fade-backdoor">
    
      <!-- Modal content-->
      <div class="modal-content" style="">
        
        <div class="modal-header">
     
    <div class="white-modal-header">
   
          <button type="button" class="close" data-dismiss="modal">&times;</button> 
           <h5 class="modal-title headerfive">About <?php print $appName ?></h5>
    
       </div>
     
        <div class="modal-body custom-height-modal" style="text-align:center">
        
        <h3 class="modal-title headerthree"><?php print $appName ?></h3>

<br/><br/>
<p><?php print $appTagline ?></p>

<p>Version <?php print $appVersion ?></p>


<p><img src="ui/images/NHLBI_Standard_Lockup_Logo_Black.png" alt="NHLBI logo and HHS logo" /></p>
        
         </div>
        
      </div>
      
    </div>
  </div>
  
<!-- End - About   -->
