
							<li  data-id="547" data-level="1" data-type="menu_item" data-class="main-menu-f" data-xicon="" data-caption="" data-alignsub="right" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-1 mega main-menu-f mega-align-right dropdown  ">
                            
  
  							<a href="" class="dropdown-toggle">Help<span class="caret"></span></a>
  
 						 	<div  data-class="" data-width="" class="tb-megamenu-submenu dropdown-menu mega-dropdown-menu nav-child">
  
  							<div class="mega-dropdown-inner">
  
    						<div  class="tb-megamenu-row row-fluid">
                            
 		 					<div  data-class="" data-width="12" style="width: 330px;" data-hidewcol="0" id="tb-megamenu-column-10" class="tb-megamenu-column span12  mega-col-nav">
                            
 		 					<div class="tb-megamenu-column-inner mega-inner clearfix">
                            
         					<ul class="tb-megamenu-subnav mega-nav level-1 items-4">
  		

                            <li  data-id="736" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">

		<span class="search-help-text">Search Help</span>

	
    <form action="" method="get" id="" accept-charset="UTF-8" class="form-search-help-menu">
		
	
		<div id="custom-search-menu-help-input" class="views-exposed-form">
        
			<div class="input-group col-md-12">
				
				<input type="text" class="search-menu-help-query form-control" placeholder="" />
                               
				<span id="custom-remove-menu-help-input">
				
                <button class="btn btn-primary" type="button" id="" value="Remove"><a href="" class="icon-remove search-help-icon-button" style="margin-top:9px;"></a>	</button>
               
                
                
				</span>
                
			</div>
            
		</div>
        
	</form>
	</li>

		<li  data-id="737" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
  <a href="" type="button" class="" data-toggle="modal" data-target="#myDashboardHelp">Browse <?php print $appName; ?> User Guide </a>
  
  </li>

		<li  data-id="738" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
  <a href="" type="button" class="" data-toggle="modal" data-target="#myDashboardStarted"> Get Started with <?php print $appName; ?> </a>
  
  </li>

		<li  data-id="739" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
  <a href="" class=""> Contact IT Service Now </a>
  
	</li>
    
    <li  data-id="739" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
  <a href="" class=""> Send Feedback about <?php print $appName; ?> </a>
  
	</li>
  
	</ul>

</div>
</div>
</div>
</div>
</div>

</li>
</ul>