<link rel="stylesheet" href="jquery-ui-1.10.3.custom/css/smoothness/jquery-ui-1.10.3.custom.min.css" type="text/css"  ></link>
<link rel="shortcut icon" href="http://www.nhlbi.nih.gov/favicon.ico" type="image/x-icon" />

<link rel="stylesheet" href="ui/css/enterprise.css" type="text/css" /></link>
<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="font-awesome-4.6.1/css/font-awesome.css">

<!-- use if neccessary  <link rel="stylesheet" href="bootstrap/css/bootstrap.css"> -->

<script type="text/javascript" src="ui/js/modernizr.min.js"></script>
<script type="text/javascript" src="ui/js/enterprise_1.js"></script>
<script type="text/javascript" src="ui/js/enterprise_2.js"></script>
<script type="text/javascript" src="ui/js/enterprise_3.js"></script>
<script type="text/javascript" src="ui/js/enterprise_4.js"></script>
<script type="text/javascript" src="ui/js/enterprise_5.js"></script>
<script type="text/javascript">
	jQuery
			.extend(
					Drupal.settings,
					{
						"extlink" : {
							"extClass" : "ext",
							"extSubdomains" : 0,
							"extExclude" : "",
							"extInclude" : "",
							"extCssExclude" : "",
							"extCssExplicit" : "",
							"extAlert" : 0,
							"extAlertText" : "This link will take you to an external web site.",
							"mailtoClass" : "mailto"
						}
					});
</script>

<script src="bootstrap/js/bootstrap.min.js"></script>
<!-- Add excape 'esc' button to close the modal -->
<script type="text/javascript">

    $(function () {
        $('.modal-dialog').modal({
            show: false,
            keyboard: true,
            backdrop: 'static'
        });
    })
</script>
<!-- modal window -->

<link rel="stylesheet" href="DataTables/media/css/jquery.dataTables_themeroller.css" type="text/css"  ></link>
<link rel="stylesheet" href="ui/css/common.css" />
<link rel="stylesheet" href="ui/css/lookup.css" />
<link rel="stylesheet" href="ui/css/jquery.multiselect.css" />
<link rel="stylesheet" href="ui/css/clinical/erap.css" />