<header id="navigation">

<div id="navigation"  style="z-index:5;">

	<nav id="main-menu" role="navigation"> 
    
    
    	<div class="region region-navigation">
    
    
    		
            <div id="block-tb-megamenu-main-menu" class="block block-tb-megamenu first last odd">      
				



                <div  data-duration="400" data-delay="200" id="tb-megamenu-main-menu" class="tb-megamenu tb-megamenu-main-menu style-nhlbi animate slide" >
				    
					<!-- removing button style
                   
					<button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar tb-megamenu-button" type="button">
					<i class="icon-reorder"></i>
				    </button>
                    
					-->
				    
    				<div class="nav-collapse collapse always-show">
    					
                        <ul  class="tb-megamenu-nav nav level-0 items-7">
                        
                        <li  data-id="547" data-level="1" data-type="menu_item" data-class="main-menu-a" data-xicon="" data-caption="" data-alignsub="right" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-1 mega main-menu-a mega-align-left dropdown x">
                        

<?php include 'appHeaderIncludes/appNameDropDown.inc'; ?>




                      
<!--                            <li  data-id="547" data-level="1" data-type="menu_item" data-class="main-menu-b" data-xicon="" data-caption="" data-alignsub="left" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-1 mega main-menu-b mega-align-left">
  
  						<a href="" class="dropdown-toggle">Home <span class="caret"></span></a>
  
  							</li>
                            
                             <li  data-id="547" data-level="1" data-type="menu_item" data-class="main-menu-c" data-xicon="" data-caption="" data-alignsub="left" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-1 mega main-menu-c mega-align-left ">
  
  						<a href="" class="dropdown-toggle">Upload <span class="caret"></span></a>
  
  							</li>
                            
                             <li  data-id="547" data-level="1" data-type="menu_item" data-class="main-menu-e" data-xicon="" data-caption="" data-alignsub="left" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-1 mega main-menu-e mega-align-left">
  
  						<a href="" class="dropdown-toggle">Registration <span class="caret"></span></a>
  
  							</li>

-->

<?php include 'appHeaderIncludes/localDropDowns.inc'; ?>

<?php include 'appHeaderIncludes/appHelp.inc'; ?>
      				
</div>
      				
</div>
</div>
</div>       
        
</nav>
     
</div>

</header>