 

<!-- add active in class to create active menu tab -->
  
  <a href="" class="dropdown-toggle">
  <span class="headline-menutitle"><?php print $appName; ?></span> <span class="caret"></span>
  </a>
  
  <div  data-class="" data-width="" class="tb-megamenu-submenu dropdown-menu mega-dropdown-menu nav-child">
  
  	<div class="mega-dropdown-inner">
  
    	<div  class="tb-megamenu-row row-fluid">
        
 		 <div  data-class="" data-width="12" style="width: 240px;" data-hidewcol="0" id="tb-megamenu-column-10" class="tb-megamenu-column span12  mega-col-nav">
         
 		 <div class="tb-megamenu-column-inner mega-inner clearfix">
         
         <ul class="tb-megamenu-subnav mega-nav level-1 items-4">
  		
        <li  data-id="736" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
  <a href="" type="button" class="" data-toggle="modal" data-target="#myDashboardAbout"> About <?php print $appName; ?> </a> <br/>

  </li>
  
          <li  data-id="736" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
         
  <a href="" type="button" class="" data-toggle="modal" data-target="#"> Release Notes </a> <br/>

  </li>
  
  	<li  data-id="738" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
   <a href="" class="" data-toggle="modal" data-target="#myDashboardSystem">System Requirements</a>
   
  </li>
  

		<li  data-id="737" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
  <a href="" class="" data-toggle="modal" data-target="#myDashboardUse"> Terms of Use </a>
  
  </li>

	

		<li  data-id="739" data-level="2" data-type="menu_item" data-class="" data-xicon="" data-caption="" data-alignsub="" data-group="0" data-hidewcol="0" data-hidesub="0" class="tb-megamenu-item level-2 mega">
        
  <a href="" class="" value="Close this window" onclick="windowClose();"> Exit to MyNHLBI </a>
  
  </li>
  
</ul>
</div>
</div>
</div>
</div>
</div>
</li>