<!-- Modal - System Requirements-->
  <div class="modal fade" id="myDashboardSystem" role="dialog" aria-labelledby="Description for System Requirements" tabindex="-1" style="background-color:#EBEBEB;" >
    <div class="modal-dialog fade-backdoor">
    
      <!-- Modal content-->
      <div class="modal-content" style="">
        
        <div class="modal-header">
     
    <div class="white-modal-header">
   
          <button type="button" class="close" data-dismiss="modal">&times;</button>
           
           <h5 class="modal-title headerfive">System Requirements</h5>
                     
       </div>
      <div class="modal-body custom-height-modal" style="text-align:center">
        
               <h3 class="modal-title headerthree"> <?php print $appName ?> </h3>

<br/><br/>
<p>Requires one of the following web browsers to run correctly</p>

<p>Internet Explorer version 9.0 or higher</p>

<p>Mozilla Firefox</p>
<p>Google Chrome</p>

<p>Safari</p>

<br/>

<button type="button" class="test" data-dismiss="modal">Test My System</button> 
  
</div>
 
</div>
      
</div>
</div>
  
<!-- End - System Requirements-->
