<!-- Modal - Get Started -->
  <div class="modal fade" id="myDashboardStarted" role="dialog" aria-labelledby="Description for Get Started" tabindex="-1" style="background-color:#EBEBEB;">
  
    <div class="modal-dialog fade-backdoor">
    
      <!-- Modal content-->
      <div class="modal-content">
        
        <div class="modal-header">
        
     
	<div class="white-modal-header">
   
		<button type="button" class="close" data-dismiss="modal">&times;</button> 
          
		<h5 class="modal-title headerfive">Get Started with <?php print $appName ?></h5>
                   
	</div>

		<h3 class="modal-title headerthree">Get Started with <?php print $appName ?></h3>

	</div>       
        
	<div class="modal-body custom-height-modal">

        <ul style="list-style:none">
         <li><a href="">Manual (PDF)</a></li>
         <li><a href="">Video tutorials</a> </li>
         <li><a href="">Training Classes</a></li>
         </ul>

         </div>

      </div>
      
    </div>
  </div>
  
<!-- End - Get Started -->