<header id="breadcrumb">
           
  <ol class="breadcrumb">
    <li><a href="#" class="" title="Home"><i class="fa fa-home fa-lg"></i></a></li>
    <li><a href="#" id="breadcrumb-link" style="">Optional Breadcrumbs</a></li>
    <li><a href="#" id="breadcrumb-link">Show Users</a></li>
    <li><a href="#" id="breadcrumb-link">Where Are They</a></li>
    <li id="breadcrumb-link" class="active">In The Workflow</li>        
  </ol>

</header>