<header id="page-header">
       
	<div id="header-wrap">
	     	
		<div class="row">
        
			<div id="name-and-slogan" class="headersize">
         
     
			<h1 id="site-name"> <a href="/" title="Home" rel="home">NHLBI <span><?php print $appName; ?></span></a></h1>
     
                
            
        	</div>
            
        	<!-- /#name-and-slogan -->
  
    		</div>
	
    
    <div class="row">
    
		<div class="col-sm-12">
			

<!-- ?php include 'appHeaderIncludes/loginModule.inc'; ? -->

            
          </div>
        
	</div>
    
</div>



	
    
    <div class="row">
    
		<div class="col-sm-12">
			
<?php include 'appHeaderIncludes/utilityModule.inc'; ?>
            
          </div>
        
	</div>
    


    
</div>



       

</header>