            <div id="header-links">
				
                <nav id="secondary-menu" role="navigation" style="height:10px;">
					<div style="float:right; margin-top:-65px;">
					
					Welcome <span>Babatunde, Kazeem (NIH/NHLBI) [E]</span> &nbsp;&nbsp;<a href="#" class="fa fa-sign-out fa-lg" style="color:#000000;text-decoration:none;" title="Log Out"></a><a href="#" style="color:#000000;text-decoration:none;" title="Log Out">Log Out</a><br />
					
					         
<span style="float:right;padding-top:4px;"><a href="#" title="Print" onclick="myFunction()" style="color: #c0143c;"><i class="fa fa-print fa-lg"></i></a> &nbsp;&nbsp;
<!--<a href="#" title="Share" style="color: #c0143c;"><i class="fa fa-share"  aria-hidden="true"></i></a> &nbsp;-->
<a value="Reset" title="Small" ONCLICK="zoomin(1.0);" style="color: #c0143c;">A</a>
<a value="Reset" title="Medium" ONCLICK="zoomin(1.15);" style="font-size:18px; color: #c0143c;">A</a>
<a value="Reset" title="Large" ONCLICK="zoomin(1.3);" style="font-size:24px; color: #c0143c;">A</a></span>
       
                    </div>
     
             
				</nav>
                
            
                
				<div class="clearfix"></div>
                
			</div>